# Generated by Django 3.1.7 on 2021-03-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmpt', '0002_auto_20210324_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustown',
            name='county_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xmpt.uscounty'),
        ),
    ]
