# Generated by Django 3.1.7 on 2021-03-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmpt', '0003_ustown_county_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustown',
            name='county_id',
        ),
    ]
